### ISSUE TITLE
Error in docker

### ISSUE THREAD

**Issue by WEDOBROADCAST** [mohif1995/Wappler_extension_xlsx_export#1]
Hi, thank you for this awesome extensions. I have try in my macbook and it working fine using development docker deployed in wappler. But after deploying to aws cloud server using production mode it show this error:

{"status":"500","message":"Module XLSXExport doesn't exist","stack":"Error: Module XLSXExport doesn't exist\n    at App._exec (/opt/node_app/lib/core/app.js:585:27)\n    at App._exec (/opt/node_app/lib/core/app.js:566:28)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async App.exec (/opt/node_app/lib/core/app.js:535:9)\n    at async App.define (/opt/node_app/lib/core/app.js:517:9)"}

I try to check in the docker webserver all the extensions and nodejs xlsx library is there. Do you have this issue with your deployment at production webserver?

Thanks

**Comment by mohif1995** [comment]
Thank you for your feedback.
I haven't tested it on docker neither aws, but it's work fine on production VPS I use.
Also please check that you upload all file
 
properly or run
```
npm i --save https://cdn.sheetjs.com/xlsx-0.19.0/xlsx-0.19.0.tgz
``` 
On your production server, it's may incompatible issue.

**Comment by WEDOBROADCAST** [comment]
Ok found the issue. Able to fix it by renaming XLSXexport.hjson to XLSXExport.hjson and XLSXexport.js to XLSXExport.js.

The issue is because in hjson the name is:

"type": "XLSXExport",
"module": "XLSXExport",
"action": "XLSXExport",

but the filename is has small letter of e instead of E which is case sensitive.

Thank you.
